apiVersion: v1
kind: ConfigMap
metadata:
  name: hostel-config
data:
  DB_SERVER: "hostel-server-2024.database.windows.net"
  DB_NAME: "hostel_management"
<<<<<<< HEAD
  PORT: "8080"
=======
<<<<<<< HEAD
  PORT: "8080"
=======
  PORT: "3001"
>>>>>>> 19dd94f0b185677226cb0f094c64f9baec816ab3
>>>>>>> ba24849c401000dfadda9388747bb615161fd56a
---
apiVersion: v1
kind: Secret
metadata:
  name: hostel-secrets
type: Opaque
data:
  DB_USER: aG9zdGVsX2FkbWlu
  DB_PASSWORD: TmlraGlsJjIwMDU=
  OPENAI_API_KEY: c2stb3ItdjEtMGMxY2NlMTdiMDZlMTZhZGY4ZmQ2NzIzZTc0MjE4YTExNzVlMmI2ODJkNGMwODNkMzJjNWEzMjVjODNiMmY1ZA==